apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "otel-collector:4318"
      isSecure: false
      protocol: http 
  metrics:
    enabled: true
  logging:
    apiLogging:
      enabled: true
