/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMessageFromDiscriminatorValue, serializeMessage, serializeMessage_NoPK, type Message, type Message_NoPK } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdGetResponse}
 */
// @ts-ignore
export function createIdGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIdGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdPatchResponse}
 */
// @ts-ignore
export function createIdPatchResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIdPatchResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdPutResponse}
 */
// @ts-ignore
export function createIdPutResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIdPutResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIdGetResponse(idGetResponse: Partial<IdGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { idGetResponse.value = n.getCollectionOfObjectValues<Message>(createMessageFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIdPatchResponse(idPatchResponse: Partial<IdPatchResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { idPatchResponse.value = n.getCollectionOfObjectValues<Message>(createMessageFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIdPutResponse(idPutResponse: Partial<IdPutResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { idPutResponse.value = n.getCollectionOfObjectValues<Message>(createMessageFromDiscriminatorValue); },
    }
}
export interface IdGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Message[] | null;
}
/**
 * Builds and executes requests for operations under /Message/id/{id}
 */
export interface IdItemRequestBuilder extends BaseRequestBuilder<IdItemRequestBuilder> {
    /**
     * Delete entity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Returns an entity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IdGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<IdItemRequestBuilderGetQueryParameters> | undefined) : Promise<IdGetResponse | undefined>;
    /**
     * Update or create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IdPatchResponse>}
     */
     patch(body: Message_NoPK, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IdPatchResponse | undefined>;
    /**
     * Replace or create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IdPutResponse>}
     */
     put(body: Message_NoPK, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IdPutResponse | undefined>;
    /**
     * Delete entity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Returns an entity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<IdItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update or create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: Message_NoPK, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Replace or create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: Message_NoPK, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns an entity.
 */
export interface IdItemRequestBuilderGetQueryParameters {
    /**
     * An opaque string that specifies the cursor position after which results should be returned.
     */
    after?: string;
    /**
     * An OData expression (an expression that returns a boolean value) using the entity's fields to retrieve a subset of the results.
     */
    filter?: string;
    /**
     * An integer value that specifies the number of items to return. Default is 100.
     */
    first?: number;
    /**
     * Uses a comma-separated list of expressions to sort response items. Add 'desc' for descending order, otherwise it's ascending by default.
     */
    orderby?: string;
    /**
     * A comma separated list of fields to return in the response.
     */
    select?: string;
}
export interface IdPatchResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Message[] | null;
}
export interface IdPutResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Message[] | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIdGetResponse(writer: SerializationWriter, idGetResponse: Partial<IdGetResponse> | undefined | null = {}) : void {
    if (idGetResponse) {
        writer.writeCollectionOfObjectValues<Message>("value", idGetResponse.value, serializeMessage);
        writer.writeAdditionalData(idGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIdPatchResponse(writer: SerializationWriter, idPatchResponse: Partial<IdPatchResponse> | undefined | null = {}) : void {
    if (idPatchResponse) {
        writer.writeCollectionOfObjectValues<Message>("value", idPatchResponse.value, serializeMessage);
        writer.writeAdditionalData(idPatchResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIdPutResponse(writer: SerializationWriter, idPutResponse: Partial<IdPutResponse> | undefined | null = {}) : void {
    if (idPutResponse) {
        writer.writeCollectionOfObjectValues<Message>("value", idPutResponse.value, serializeMessage);
        writer.writeAdditionalData(idPutResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const IdItemRequestBuilderUriTemplate = "{+baseurl}/Message/id/{id}{?%24after*,%24filter*,%24first*,%24orderby*,%24select*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const IdItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "after": "%24after",
    "filter": "%24filter",
    "first": "%24first",
    "orderby": "%24orderby",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const IdItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: IdItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: IdItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createIdGetResponseFromDiscriminatorValue,
        queryParametersMapper: IdItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: IdItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createIdPatchResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMessage_NoPK,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
    put: {
        uriTemplate: IdItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createIdPutResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMessage_NoPK,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
