/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatRequestBuilderNavigationMetadata, ChatRequestBuilderRequestsMetadata, type ChatRequestBuilder } from './chat/index.js';
// @ts-ignore
import { DocumentRequestBuilderNavigationMetadata, DocumentRequestBuilderRequestsMetadata, type DocumentRequestBuilder } from './document/index.js';
// @ts-ignore
import { MessageRequestBuilderNavigationMetadata, MessageRequestBuilderRequestsMetadata, type MessageRequestBuilder } from './message/index.js';
// @ts-ignore
import { SuggestionRequestBuilderNavigationMetadata, SuggestionRequestBuilderRequestsMetadata, type SuggestionRequestBuilder } from './suggestion/index.js';
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata, UserRequestBuilderRequestsMetadata } from './user/index.js';
// @ts-ignore
import { type VoteRequestBuilder, VoteRequestBuilderNavigationMetadata, VoteRequestBuilderRequestsMetadata } from './vote/index.js';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link DabClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createDabClient(requestAdapter: RequestAdapter) {
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "http://dab:5000/api";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<DabClient>(requestAdapter, pathParameters, DabClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface DabClient extends BaseRequestBuilder<DabClient> {
    /**
     * The Chat property
     */
    get chat(): ChatRequestBuilder;
    /**
     * The Document property
     */
    get document(): DocumentRequestBuilder;
    /**
     * The Message property
     */
    get message(): MessageRequestBuilder;
    /**
     * The Suggestion property
     */
    get suggestion(): SuggestionRequestBuilder;
    /**
     * The User property
     */
    get user(): UserRequestBuilder;
    /**
     * The Vote property
     */
    get vote(): VoteRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DabClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DabClientNavigationMetadata: Record<Exclude<keyof DabClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chat: {
        requestsMetadata: ChatRequestBuilderRequestsMetadata,
        navigationMetadata: ChatRequestBuilderNavigationMetadata,
    },
    document: {
        requestsMetadata: DocumentRequestBuilderRequestsMetadata,
        navigationMetadata: DocumentRequestBuilderNavigationMetadata,
    },
    message: {
        requestsMetadata: MessageRequestBuilderRequestsMetadata,
        navigationMetadata: MessageRequestBuilderNavigationMetadata,
    },
    suggestion: {
        requestsMetadata: SuggestionRequestBuilderRequestsMetadata,
        navigationMetadata: SuggestionRequestBuilderNavigationMetadata,
    },
    user: {
        requestsMetadata: UserRequestBuilderRequestsMetadata,
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
    vote: {
        requestsMetadata: VoteRequestBuilderRequestsMetadata,
        navigationMetadata: VoteRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
