/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createChatFromDiscriminatorValue, serializeChat, type Chat } from '../models/index.js';
// @ts-ignore
import { IdRequestBuilderNavigationMetadata, type IdRequestBuilder } from './id/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChatGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The nextLink property
     */
    nextLink?: string | null;
    /**
     * The value property
     */
    value?: Chat[] | null;
}
export interface ChatPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Chat[] | null;
}
/**
 * Builds and executes requests for operations under /Chat
 */
export interface ChatRequestBuilder extends BaseRequestBuilder<ChatRequestBuilder> {
    /**
     * The id property
     */
    get id(): IdRequestBuilder;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChatGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<ChatRequestBuilderGetQueryParameters> | undefined) : Promise<ChatGetResponse | undefined>;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChatPostResponse>}
     */
     post(body: Chat, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChatPostResponse | undefined>;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ChatRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Chat, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns entities.
 */
export interface ChatRequestBuilderGetQueryParameters {
    /**
     * An opaque string that specifies the cursor position after which results should be returned.
     */
    after?: string;
    /**
     * An OData expression (an expression that returns a boolean value) using the entity's fields to retrieve a subset of the results.
     */
    filter?: string;
    /**
     * An integer value that specifies the number of items to return. Default is 100.
     */
    first?: number;
    /**
     * Uses a comma-separated list of expressions to sort response items. Add 'desc' for descending order, otherwise it's ascending by default.
     */
    orderby?: string;
    /**
     * A comma separated list of fields to return in the response.
     */
    select?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChatGetResponse}
 */
// @ts-ignore
export function createChatGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChatGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChatPostResponse}
 */
// @ts-ignore
export function createChatPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChatPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChatGetResponse(chatGetResponse: Partial<ChatGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "nextLink": n => { chatGetResponse.nextLink = n.getStringValue(); },
        "value": n => { chatGetResponse.value = n.getCollectionOfObjectValues<Chat>(createChatFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChatPostResponse(chatPostResponse: Partial<ChatPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { chatPostResponse.value = n.getCollectionOfObjectValues<Chat>(createChatFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChatGetResponse(writer: SerializationWriter, chatGetResponse: Partial<ChatGetResponse> | undefined | null = {}) : void {
    if (chatGetResponse) {
        writer.writeStringValue("nextLink", chatGetResponse.nextLink);
        writer.writeCollectionOfObjectValues<Chat>("value", chatGetResponse.value, serializeChat);
        writer.writeAdditionalData(chatGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChatPostResponse(writer: SerializationWriter, chatPostResponse: Partial<ChatPostResponse> | undefined | null = {}) : void {
    if (chatPostResponse) {
        writer.writeCollectionOfObjectValues<Chat>("value", chatPostResponse.value, serializeChat);
        writer.writeAdditionalData(chatPostResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const ChatRequestBuilderUriTemplate = "{+baseurl}/Chat{?%24after*,%24filter*,%24first*,%24orderby*,%24select*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ChatRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "after": "%24after",
    "filter": "%24filter",
    "first": "%24first",
    "orderby": "%24orderby",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    id: {
        navigationMetadata: IdRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ChatRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ChatRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createChatGetResponseFromDiscriminatorValue,
        queryParametersMapper: ChatRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ChatRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createChatPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChat,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
