/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithMessageItemRequestBuilder, WithMessageItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Vote/chatId/{chatId}/messageId
 */
export interface MessageIdRequestBuilder extends BaseRequestBuilder<MessageIdRequestBuilder> {
    /**
     * Gets an item from the Kiota.Vote.chatId.item.messageId.item collection
     * @param messageId Unique identifier of the item
     * @returns {WithMessageItemRequestBuilder}
     */
     byMessageId(messageId: string) : WithMessageItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MessageIdRequestBuilderUriTemplate = "{+baseurl}/Vote/chatId/{chatId}/messageId";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MessageIdRequestBuilderNavigationMetadata: Record<Exclude<keyof MessageIdRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byMessageId: {
        requestsMetadata: WithMessageItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["messageId"],
    },
};
/* tslint:enable */
/* eslint-enable */
