receivers:
  otlp/gateway:
    protocols:
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - http://localhost
            - https://*
          allowed_headers:
            - "Content-Type"
            - "X-Api-Key"
            - "X-Faro-Session-Id"
          max_age: 7200
        endpoint: "0.0.0.0:4318"
