pg_stat_statements:
  query: >
    SELECT
      pg_get_userbyid(userid) as user,
      pg_database.datname,
      pg_stat_statements.queryid,
      pg_stat_statements.query,
      pg_stat_statements.calls,
      pg_stat_statements.total_exec_time AS time_milliseconds,
      pg_stat_statements.rows,
      pg_stat_statements.shared_blks_hit,
      pg_stat_statements.shared_blks_read,
      pg_stat_statements.shared_blks_dirtied,
      pg_stat_statements.shared_blks_written,
      pg_stat_statements.local_blks_hit,
      pg_stat_statements.local_blks_read,
      pg_stat_statements.local_blks_dirtied,
      pg_stat_statements.local_blks_written,
      pg_stat_statements.temp_blks_read,
      pg_stat_statements.temp_blks_written,
      pg_stat_statements.shared_blk_read_time,
      pg_stat_statements.shared_blk_write_time,
      pg_stat_statements.local_blk_read_time,
      pg_stat_statements.local_blk_write_time,
      pg_stat_statements.temp_blk_read_time,
      pg_stat_statements.temp_blk_write_time
    FROM pg_stat_statements
    JOIN pg_database
      ON pg_database.oid = pg_stat_statements.dbid
  metrics:
    - user:
        usage: "LABEL"
        description: "User who executed the statement"
    - datname:
        usage: "LABEL"
        description: "Database in which the statement was executed"
    - queryid:
        usage: "LABEL"
        description: "Hash code computed from the statement's parse tree"
    - query:
        usage: "LABEL"
        description: "Normalized or raw query text"
    - calls:
        usage: "COUNTER"
        description: "Number of times the statement was executed"
    - time_milliseconds:
        usage: "COUNTER"
        description: "Total time spent in the statement, in milliseconds"
    - rows:
        usage: "COUNTER"
        description: "Total rows retrieved or affected by the statement"
    - shared_blks_hit:
        usage: "COUNTER"
        description: "Number of shared block cache hits"
    - shared_blks_read:
        usage: "COUNTER"
        description: "Number of shared blocks read"
    - shared_blks_dirtied:
        usage: "COUNTER"
        description: "Number of shared blocks dirtied"
    - shared_blks_written:
        usage: "COUNTER"
        description: "Number of shared blocks written"
    - local_blks_hit:
        usage: "COUNTER"
        description: "Number of local block cache hits"
    - local_blks_read:
        usage: "COUNTER"
        description: "Number of local blocks read"
    - local_blks_dirtied:
        usage: "COUNTER"
        description: "Number of local blocks dirtied"
    - local_blks_written:
        usage: "COUNTER"
        description: "Number of local blocks written"
    - temp_blks_read:
        usage: "COUNTER"
        description: "Number of temp blocks read"
    - temp_blks_written:
        usage: "COUNTER"
        description: "Number of temp blocks written"
    - shared_blk_read_time:
        usage: "COUNTER"
        description: "Time spent reading shared blocks (ms)"
    - shared_blk_write_time:
        usage: "COUNTER"
        description: "Time spent writing shared blocks (ms)"
    - local_blk_read_time:
        usage: "COUNTER"
        description: "Time spent reading local blocks (ms)"
    - local_blk_write_time:
        usage: "COUNTER"
        description: "Time spent writing local blocks (ms)"
    - temp_blk_read_time:
        usage: "COUNTER"
        description: "Time spent reading temp blocks (ms)"
    - temp_blk_write_time:
        usage: "COUNTER"
        description: "Time spent writing temp blocks (ms)"
