/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithChatItemRequestBuilder, WithChatItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Vote/chatId
 */
export interface ChatIdRequestBuilder extends BaseRequestBuilder<ChatIdRequestBuilder> {
    /**
     * Gets an item from the Kiota.Vote.chatId.item collection
     * @param chatId Unique identifier of the item
     * @returns {WithChatItemRequestBuilder}
     */
     byChatId(chatId: string) : WithChatItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatIdRequestBuilderUriTemplate = "{+baseurl}/Vote/chatId";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatIdRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatIdRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byChatId: {
        navigationMetadata: WithChatItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["chatId"],
    },
};
/* tslint:enable */
/* eslint-enable */
