/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithCreatedAtItemRequestBuilder, WithCreatedAtItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Document/id/{id}/createdAt
 */
export interface CreatedAtRequestBuilder extends BaseRequestBuilder<CreatedAtRequestBuilder> {
    /**
     * Gets an item from the Kiota.Document.id.item.createdAt.item collection
     * @param createdAt Unique identifier of the item
     * @returns {WithCreatedAtItemRequestBuilder}
     */
     byCreatedAt(createdAt: string) : WithCreatedAtItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CreatedAtRequestBuilderUriTemplate = "{+baseurl}/Document/id/{id}/createdAt";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CreatedAtRequestBuilderNavigationMetadata: Record<Exclude<keyof CreatedAtRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCreatedAt: {
        requestsMetadata: WithCreatedAtItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["createdAt"],
    },
};
/* tslint:enable */
/* eslint-enable */
