/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MessageIdRequestBuilderNavigationMetadata, type MessageIdRequestBuilder } from './messageId/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Vote/chatId/{chatId}
 */
export interface WithChatItemRequestBuilder extends BaseRequestBuilder<WithChatItemRequestBuilder> {
    /**
     * The messageId property
     */
    get messageId(): MessageIdRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithChatItemRequestBuilderUriTemplate = "{+baseurl}/Vote/chatId/{chatId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithChatItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithChatItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    messageId: {
        navigationMetadata: MessageIdRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
