receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
        include_metadata: true
        cors:
          allowed_origins:
            - http://localhost
            - https://*
          allowed_headers:
            - "Content-Type"
            - "X-Api-Key"
            - "X-Faro-Session-Id"
          max_age: 7200

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp/mimir:
    endpoint: http://mimir:9009/otlp
  otlphttp/loki:
    endpoint: http://loki:3100/otlp 
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/pyroscope:
    endpoint: "http://pyroscope:4040"
    tls:
      insecure: true
  # clickhouse:
  #   endpoint: tcp://clickhouse:9000
  #   # ttl: 72h
  #   traces_table_name: otel_traces
  #   logs_table_name: otel_logs
  #   create_schema: true
  #   timeout: 5s
  #   database: default
  #   sending_queue:
  #     queue_size: 1000
  #   retry_on_failure:
  #     enabled: true
  #     initial_interval: 5s
  #     max_interval: 30s
  #     max_elapsed_time: 300s
  #   username: "username"
  #   password: "password"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/mimir]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]
    # profiles:
    #   receivers: [otlp]
    #   exporters: [otlp/pyroscope]
  telemetry:
    metrics:
      level: detailed
    logs:
      level: info


