auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    # Remove 'shared_store'; it's not recognized in newer Loki versions.
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  # 'enforce_metric_name' was removed; remove it from config.
  reject_old_samples: true
  reject_old_samples_max_age: 168h
