receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:

exporters:
  debug:
  otlp:
    endpoint: "grafana:4317"
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    tls:
      insecure: true
  otlphttp/traceloop:
    endpoint: "https://api.traceloop.com" 
    headers:
      "Authorization": "Bearer ${env:TRACELOOP_API_KEY}"

extensions:
  health_check:
  pprof:
  zpages:


service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlp/jaeger, otlphttp/traceloop, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlp/jaeger, debug]