receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
        cors:
          allowed_origins:
            - http://*
            - https://*
  httpcheck/frontend:
    targets:
      - endpoint: http://frontend:3000
  docker_stats:
    endpoint: unix:///var/run/docker.sock
  filelog:
    include_file_path: true
    include:
      - ./psql_logs/*.log
    operators:
      - id: container-parser
        type: container
      - type: trace_parser
        trace_id:
          parse_from: attributes.traceId
        span_id:
          parse_from: attributes.spanId
        trace_flags:
          parse_from: attributes.traceFlags

  # Host metrics
  hostmetrics:
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      load:
      filesystem:
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      paging:
      processes:
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  otlphttp/tempo:
    endpoint: "http://tempo:3200"
    tls:
      insecure: true
  opensearch/traces:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
    timeout:
    retry_on_failure:
      enabled: true
      initial_interval: 100000000
      randomization_factor: 0.5
    dataset: traces
  opensearch/logs:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
    timeout:
    retry_on_failure:
      enabled: true
      initial_interval: 100000000
      randomization_factor: 0.5
    dataset: logs
  otlp/traces:
    endpoint: "data-prepper:21890"
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/metrics:
    endpoint: "data-prepper:21891"
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/logs:
    endpoint: "data-prepper:21892"
    tls:
      insecure: true
      insecure_skip_verify: true
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: true
    timeout: 60s
    tls:
      insecure_skip_verify: true
  otlphttp/traceloop:
    endpoint: "https://api.traceloop.com" 
    headers:
      "Authorization": "Bearer ${env:TRACELOOP_API_KEY}"
  otlphttp/betterstack:
    endpoint: "https://s1202625.eu-nbg-2.betterstackdata.com"
    headers:
      Authorization: "Bearer zYyRMpCtN1ipLRpJQQKDeW16"
  azuredataexplorer:
    cluster_uri: "https://azdexplorer.northcentralus.kusto.windows.net"
    application_id: "11d953d9-3ed7-4f8c-92d0-a6c311dba3f1"
    application_key: "${env:AZURE_STORAGE_EXPLORER_KEY}"
    tenant_id: "0c4da9c5-40ea-4e7d-9c7a-e7308d4f8e38"
    db_name: "db"
    metrics_table_name: "metrics"
    logs_table_name: "logs"
    traces_table_name: "traces"
    ingestion_type : "managed"
  kafka:
    brokers:
      - localhost:9092
    protocol_version: 2.0.0
  file/no_rotation:
    path: ./logs/logs.json
  clickhouse:
    endpoint: ${env:CLICKHOUSE_CLOUD_ENDPOINT}
    # ttl: 72h
    traces_table_name: traces
    logs_table_name: logs
    create_schema: true
    timeout: 5s
    database: default
    sending_queue:
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    username: "default"
    password: ${env:CLICKHOUSE_CLOUD_PASSWORD}
  # azureblobexporter:
  #   url: "https://otelstorage2312.blob.core.windows.net/"
  #   container:
  #     logs: "logs"
  #     metrics: "metrics"
  #     traces: "traces"
  #   auth:
  #     type: "connection_string"
  #     connection_string: "DefaultEndpointsProtocol=https;AccountName=otelstorage2312;AccountKey=${env:AZURE_OTEL_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net"

processors:
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["test"], instrumentation_scope.name)
  batch:
    send_batch_size: 100000
    timeout: 5s
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500
  resourcedetection/system:
    detectors: [ "system" ]
    system:
      hostname_sources: [ "os" ]
  resource:
    attributes:
      - key: service.name
        value: "serviceName"
        action: upsert

connectors:
  spanmetrics:
    dimensions_cache_size: 1000
    metrics_flush_interval: 15s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [ memory_limiter, resourcedetection/system, resource, batch ]
      exporters: [clickhouse, debug, spanmetrics]
    metrics:
      receivers: [hostmetrics, docker_stats, httpcheck/frontend, otlp, prometheus, spanmetrics]
      processors: [batch]
      exporters: [clickhouse, debug]
    logs:
      receivers: [otlp]
      processors: [ memory_limiter, resourcedetection/system, resource, batch ]
      exporters: [clickhouse, debug]