server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_binary:
        thrift_compact:
        grpc:
    otlp:
      protocols:
        grpc:
        http:
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
