/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVoteFromDiscriminatorValue, serializeVote, type Vote } from '../models/index.js';
// @ts-ignore
import { ChatIdRequestBuilderNavigationMetadata, type ChatIdRequestBuilder } from './chatId/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VoteGetResponse}
 */
// @ts-ignore
export function createVoteGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVoteGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VotePostResponse}
 */
// @ts-ignore
export function createVotePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVotePostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVoteGetResponse(voteGetResponse: Partial<VoteGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "nextLink": n => { voteGetResponse.nextLink = n.getStringValue(); },
        "value": n => { voteGetResponse.value = n.getCollectionOfObjectValues<Vote>(createVoteFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVotePostResponse(votePostResponse: Partial<VotePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { votePostResponse.value = n.getCollectionOfObjectValues<Vote>(createVoteFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVoteGetResponse(writer: SerializationWriter, voteGetResponse: Partial<VoteGetResponse> | undefined | null = {}) : void {
    if (voteGetResponse) {
        writer.writeStringValue("nextLink", voteGetResponse.nextLink);
        writer.writeCollectionOfObjectValues<Vote>("value", voteGetResponse.value, serializeVote);
        writer.writeAdditionalData(voteGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVotePostResponse(writer: SerializationWriter, votePostResponse: Partial<VotePostResponse> | undefined | null = {}) : void {
    if (votePostResponse) {
        writer.writeCollectionOfObjectValues<Vote>("value", votePostResponse.value, serializeVote);
        writer.writeAdditionalData(votePostResponse.additionalData);
    }
}
export interface VoteGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The nextLink property
     */
    nextLink?: string | null;
    /**
     * The value property
     */
    value?: Vote[] | null;
}
export interface VotePostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Vote[] | null;
}
/**
 * Builds and executes requests for operations under /Vote
 */
export interface VoteRequestBuilder extends BaseRequestBuilder<VoteRequestBuilder> {
    /**
     * The chatId property
     */
    get chatId(): ChatIdRequestBuilder;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VoteGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<VoteRequestBuilderGetQueryParameters> | undefined) : Promise<VoteGetResponse | undefined>;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VotePostResponse>}
     */
     post(body: Vote, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VotePostResponse | undefined>;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<VoteRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Vote, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns entities.
 */
export interface VoteRequestBuilderGetQueryParameters {
    /**
     * An opaque string that specifies the cursor position after which results should be returned.
     */
    after?: string;
    /**
     * An OData expression (an expression that returns a boolean value) using the entity's fields to retrieve a subset of the results.
     */
    filter?: string;
    /**
     * An integer value that specifies the number of items to return. Default is 100.
     */
    first?: number;
    /**
     * Uses a comma-separated list of expressions to sort response items. Add 'desc' for descending order, otherwise it's ascending by default.
     */
    orderby?: string;
    /**
     * A comma separated list of fields to return in the response.
     */
    select?: string;
}
/**
 * Uri template for the request builder.
 */
export const VoteRequestBuilderUriTemplate = "{+baseurl}/Vote{?%24after*,%24filter*,%24first*,%24orderby*,%24select*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const VoteRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "after": "%24after",
    "filter": "%24filter",
    "first": "%24first",
    "orderby": "%24orderby",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VoteRequestBuilderNavigationMetadata: Record<Exclude<keyof VoteRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chatId: {
        navigationMetadata: ChatIdRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VoteRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VoteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createVoteGetResponseFromDiscriminatorValue,
        queryParametersMapper: VoteRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: VoteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createVotePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVote,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
