apiversion: v1alpha1
contexts:
    default:
        name: default
    dev:
        grafana:
            url: http://grafana:3000
        name: dev
        output-format: json
        targets:
            - Dashboard
            - DashboardFolder
current-context: dev

