/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDocumentFromDiscriminatorValue, serializeDocument, type Document } from '../models/index.js';
// @ts-ignore
import { IdRequestBuilderNavigationMetadata, type IdRequestBuilder } from './id/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DocumentGetResponse}
 */
// @ts-ignore
export function createDocumentGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDocumentGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DocumentPostResponse}
 */
// @ts-ignore
export function createDocumentPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDocumentPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDocumentGetResponse(documentGetResponse: Partial<DocumentGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "nextLink": n => { documentGetResponse.nextLink = n.getStringValue(); },
        "value": n => { documentGetResponse.value = n.getCollectionOfObjectValues<Document>(createDocumentFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDocumentPostResponse(documentPostResponse: Partial<DocumentPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { documentPostResponse.value = n.getCollectionOfObjectValues<Document>(createDocumentFromDiscriminatorValue); },
    }
}
export interface DocumentGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The nextLink property
     */
    nextLink?: string | null;
    /**
     * The value property
     */
    value?: Document[] | null;
}
export interface DocumentPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The value property
     */
    value?: Document[] | null;
}
/**
 * Builds and executes requests for operations under /Document
 */
export interface DocumentRequestBuilder extends BaseRequestBuilder<DocumentRequestBuilder> {
    /**
     * The id property
     */
    get id(): IdRequestBuilder;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DocumentGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<DocumentRequestBuilderGetQueryParameters> | undefined) : Promise<DocumentGetResponse | undefined>;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DocumentPostResponse>}
     */
     post(body: Document, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DocumentPostResponse | undefined>;
    /**
     * Returns entities.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DocumentRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create entity.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Document, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns entities.
 */
export interface DocumentRequestBuilderGetQueryParameters {
    /**
     * An opaque string that specifies the cursor position after which results should be returned.
     */
    after?: string;
    /**
     * An OData expression (an expression that returns a boolean value) using the entity's fields to retrieve a subset of the results.
     */
    filter?: string;
    /**
     * An integer value that specifies the number of items to return. Default is 100.
     */
    first?: number;
    /**
     * Uses a comma-separated list of expressions to sort response items. Add 'desc' for descending order, otherwise it's ascending by default.
     */
    orderby?: string;
    /**
     * A comma separated list of fields to return in the response.
     */
    select?: string;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDocumentGetResponse(writer: SerializationWriter, documentGetResponse: Partial<DocumentGetResponse> | undefined | null = {}) : void {
    if (documentGetResponse) {
        writer.writeStringValue("nextLink", documentGetResponse.nextLink);
        writer.writeCollectionOfObjectValues<Document>("value", documentGetResponse.value, serializeDocument);
        writer.writeAdditionalData(documentGetResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDocumentPostResponse(writer: SerializationWriter, documentPostResponse: Partial<DocumentPostResponse> | undefined | null = {}) : void {
    if (documentPostResponse) {
        writer.writeCollectionOfObjectValues<Document>("value", documentPostResponse.value, serializeDocument);
        writer.writeAdditionalData(documentPostResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const DocumentRequestBuilderUriTemplate = "{+baseurl}/Document{?%24after*,%24filter*,%24first*,%24orderby*,%24select*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const DocumentRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "after": "%24after",
    "filter": "%24filter",
    "first": "%24first",
    "orderby": "%24orderby",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    id: {
        navigationMetadata: IdRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DocumentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createDocumentGetResponseFromDiscriminatorValue,
        queryParametersMapper: DocumentRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: DocumentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createDocumentPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDocument,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
